language: node_js
node_js:
- '12'
dist: xenial
addons:
  postgresql: '10'
services:
- docker
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
script:
- yarn lint
- yarn test
branches:
  only:
  - production
  - master
deploy:
  provider: heroku
  api_key:
    secure: edsWACJVylm6eoys5NOLp1GlxyLCroqzejKTbeniK/WFQXHPeyZDKf6IX9TcLfcmgNNLhkY4WSA1EYBU+po8cOf+mSOUURiF0Mq5PuOwgp0AKU1qv2RCZJ9MiStDGPDqRBmJSnmLenMXdXhe6310ZhJydMFmbwlFKHMGBK7JL4/lDRJNpKWdCvvWVH24e6YfyQmRzMquHPmgaf0jvMDBtFMcw2CGyrcKyj3mmDvTSc/sZkfI9lhvPWtXlblqmGoeQZXbQxSpfzhiefL2XAI7lPABs+AeP3myTdnSK7qRkvGxkAQZ+jZrf3PCd9a8mTn2TBqv0IzXTmACmjIa5kOrR6pOJuOdLrg/Xmsoj/6c3V5HyXA6IPf+aHzw9ZRs0z7OJPmWCnJ5XixzdS8cDHtWkLEgdV0J4idoHB1IuK0rYmnYdjUwXDY8Sz8bAbqkhh8VUVl55s0YTrUni8I16enu0MWi3GwCEBphHpmZKeffyQEZ0C7zK0OllwRhugrBq0w4ZlFfDYLdfMHAEYbZjml92RwGFarrYnLDHdmUoOpkSi6KHy6xzt24gtuwbu3IOZdBJOf05GYcEqq4xC92L26/68NSXxmKWUmm0H00/riKJ0PjDEt9m1Dl+Fh2dnWR3Y4RwCxpzSdyObFYr6CuflPvZNpHWNzbiQMUzCLG08zuC2A=
  app:
    master: rallio-chute-service-s
    production: rallio-chute-service
  run:
  - yarn db:migrate
notifications:
  slack:
    rooms:
    - rallio:7g71eH41LnE5nYQcG6cTBcFb#travis-notifications
